---
- name: Delete Floating IP
  os_floating_ip:
    cloud: ospcloud
    server: "{{ item.name }}"
    network: ext_network
    state: absent
  register: instancefloatingip
  tags: osp_instance 

# tasks file for osp.servers
- name:  Delete Server
  os_server:
    cloud: ospcloud
    name: "{{ item.name }}"
    network: int_network
    state: absent
  tags: osp_instance
