---
# tasks file for lb-tier
- name: Install All Required packages
  package:
    name: "{{ packages }}"
    state: latest

- name: Start HAProxy
  service:
    name: haproxy
    state: started
    enabled: yes
  notify: restart HAproxy


- name: configure haproxy
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: restart HAproxy